// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using registroAsistencia.Data;

#nullable disable

namespace registroAsistencia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250912015200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("registroAsistencia.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QrAlumnoBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("registroAsistencia.Models.AlumnoCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("AlumnoId", "CursoId")
                        .IsUnique();

                    b.ToTable("AlumnoCursos");
                });

            modelBuilder.Entity("registroAsistencia.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MarcadaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("AlumnoId", "ClaseId")
                        .IsUnique();

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("registroAsistencia.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RamoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RamoId");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("registroAsistencia.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("registroAsistencia.Models.QrClaseToken", b =>
                {
                    b.Property<string>("Nonce")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ClaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Nonce");

                    b.HasIndex("ClaseId");

                    b.ToTable("QrClaseTokens");
                });

            modelBuilder.Entity("registroAsistencia.Models.Ramo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId", "Codigo")
                        .IsUnique();

                    b.ToTable("Ramos");
                });

            modelBuilder.Entity("registroAsistencia.Models.AlumnoCurso", b =>
                {
                    b.HasOne("registroAsistencia.Models.Alumno", "Alumno")
                        .WithMany("AlumnoCursos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("registroAsistencia.Models.Curso", "Curso")
                        .WithMany("AlumnoCursos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("registroAsistencia.Models.Asistencia", b =>
                {
                    b.HasOne("registroAsistencia.Models.Alumno", null)
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("registroAsistencia.Models.Clase", null)
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("registroAsistencia.Models.Clase", b =>
                {
                    b.HasOne("registroAsistencia.Models.Ramo", "Ramo")
                        .WithMany("Clases")
                        .HasForeignKey("RamoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ramo");
                });

            modelBuilder.Entity("registroAsistencia.Models.QrClaseToken", b =>
                {
                    b.HasOne("registroAsistencia.Models.Clase", null)
                        .WithMany()
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("registroAsistencia.Models.Ramo", b =>
                {
                    b.HasOne("registroAsistencia.Models.Curso", "Curso")
                        .WithMany("Ramos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("registroAsistencia.Models.Alumno", b =>
                {
                    b.Navigation("AlumnoCursos");
                });

            modelBuilder.Entity("registroAsistencia.Models.Curso", b =>
                {
                    b.Navigation("AlumnoCursos");

                    b.Navigation("Ramos");
                });

            modelBuilder.Entity("registroAsistencia.Models.Ramo", b =>
                {
                    b.Navigation("Clases");
                });
#pragma warning restore 612, 618
        }
    }
}
